import type { CardDef } from '../types.js';

// House Kessler — "Ironbound". Tanky, attrition, repair/Bulwark themed. 15 unique cards,
// intended to be run at 2 copies each in a 30-card starter deck. See docs/lore.md.
export const KESSLER_CARDS: CardDef[] = [
  {
    type: 'unit',
    defId: 'kessler_mining_drone',
    name: 'Mining Drone',
    faction: 'kessler',
    unitKind: 'creature',
    cost: 1,
    attack: 1,
    hull: 3,
    shields: 0,
    keywords: [],
    flavor: 'Built to survive a cave-in. Repurposed to survive worse.',
  },
  {
    type: 'order',
    defId: 'kessler_salvage_charge',
    name: 'Salvage Charge',
    faction: 'kessler',
    cost: 1,
    effects: [{ kind: 'damage', amount: 2, target: 'enemyUnit' }],
    description: 'Deal 2 damage to an enemy unit.',
    flavor: 'Demolition charges, repointed.',
  },
  {
    type: 'unit',
    defId: 'kessler_ironclad_skiff',
    name: 'Ironclad Skiff',
    faction: 'kessler',
    unitKind: 'ship',
    cost: 2,
    attack: 2,
    hull: 3,
    shields: 1,
    keywords: [],
    flavor: 'Slow. Ugly. Still flying after three border wars.',
  },
  {
    type: 'module',
    defId: 'kessler_bulkhead_plating',
    name: 'Bulkhead Plating',
    faction: 'kessler',
    cost: 2,
    attackBonus: 0,
    hullBonus: 3,
    shieldBonus: 0,
    keywordsGranted: ['bulwark'],
    flavor: 'Everyone hides behind the Kessler ships. That is the point.',
  },
  {
    type: 'unit',
    defId: 'kessler_scrap_crawler',
    name: 'Scrap Crawler',
    faction: 'kessler',
    unitKind: 'creature',
    cost: 2,
    attack: 2,
    hull: 2,
    shields: 0,
    keywords: [],
    ability: { trigger: 'onDeath', effects: [{ kind: 'draw', amount: 1 }], description: 'When destroyed, draw a card.' },
    flavor: 'It scavenges even its own wreckage for one last part.',
  },
  {
    type: 'unit',
    defId: 'kessler_foundry_tender',
    name: 'Foundry Tender',
    faction: 'kessler',
    unitKind: 'creature',
    cost: 3,
    attack: 1,
    hull: 4,
    shields: 2,
    keywords: [],
    ability: { trigger: 'onPlay', effects: [{ kind: 'heal', amount: 2, target: 'friendlyUnit' }], description: 'When deployed, restore 2 Hull to a friendly unit.' },
    flavor: 'Aldric keeps one of these on every ship. His mother taught him that.',
  },
  {
    type: 'unit',
    defId: 'kessler_frigate',
    name: 'Kessler Frigate',
    faction: 'kessler',
    unitKind: 'ship',
    cost: 3,
    attack: 3,
    hull: 4,
    shields: 1,
    keywords: [],
    flavor: 'The workhorse of the Ironbound line.',
  },
  {
    type: 'order',
    defId: 'kessler_emergency_patch',
    name: 'Emergency Patch',
    faction: 'kessler',
    cost: 3,
    effects: [{ kind: 'heal', amount: 5, target: 'friendlyUnit' }],
    description: 'Restore 5 Hull to a friendly unit.',
    flavor: '"Weld it, don\'t replace it." — House Kessler engineering motto.',
  },
  {
    type: 'unit',
    defId: 'kessler_siege_hauler',
    name: 'Siege Hauler',
    faction: 'kessler',
    unitKind: 'ship',
    cost: 4,
    attack: 3,
    hull: 6,
    shields: 2,
    keywords: ['bulwark'],
    flavor: 'It was built to haul ore through a warzone. It hauls the warzone now.',
  },
  {
    type: 'module',
    defId: 'kessler_mass_driver_array',
    name: 'Mass Driver Array',
    faction: 'kessler',
    cost: 4,
    attackBonus: 3,
    hullBonus: 0,
    shieldBonus: 0,
    keywordsGranted: [],
    flavor: 'Mining equipment with the safeties removed.',
  },
  {
    type: 'unit',
    defId: 'kessler_ironbound_veteran',
    name: 'Ironbound Veteran',
    faction: 'kessler',
    unitKind: 'creature',
    cost: 5,
    attack: 4,
    hull: 5,
    shields: 1,
    keywords: ['boarding'],
    flavor: 'She has boarded more enemy wrecks than she can count.',
  },
  {
    type: 'unit',
    defId: 'kessler_bastion_cruiser',
    name: 'Bastion-Class Cruiser',
    faction: 'kessler',
    unitKind: 'ship',
    cost: 5,
    attack: 4,
    hull: 7,
    shields: 2,
    keywords: ['bulwark'],
    flavor: 'Named for the thing it does, not the way it looks.',
  },
  {
    type: 'module',
    defId: 'kessler_reactive_armor',
    name: 'Reactive Armor Plating',
    faction: 'kessler',
    cost: 6,
    attackBonus: 0,
    hullBonus: 2,
    shieldBonus: 3,
    keywordsGranted: [],
    flavor: 'Learns from every hit. Slowly. Painfully.',
  },
  {
    type: 'order',
    defId: 'kessler_orbital_barrage',
    name: 'Orbital Barrage',
    faction: 'kessler',
    cost: 6,
    effects: [{ kind: 'damage', amount: 5, target: 'enemyUnit' }],
    description: 'Deal 5 damage to an enemy unit.',
    flavor: 'A mining charge, dropped from very high up.',
  },
  {
    type: 'unit',
    defId: 'kessler_dreadnought_prime',
    name: 'Dreadnought Kessler-Prime',
    faction: 'kessler',
    unitKind: 'ship',
    cost: 7,
    attack: 6,
    hull: 10,
    shields: 3,
    keywords: ['bulwark'],
    flavor: 'The last ship House Kessler ever built together, before the Pact broke.',
  },
];
