import type { CardDef } from '../types.js';

// House Voss — "The Unbroken Current". Aggressive tempo, energy weapons, Overload
// risk/reward. 15 unique cards, run at 2 copies each in a 30-card starter deck.
export const VOSS_CARDS: CardDef[] = [
  {
    type: 'unit',
    defId: 'voss_static_wisp',
    name: 'Static Wisp',
    faction: 'voss',
    unitKind: 'creature',
    cost: 1,
    attack: 2,
    hull: 1,
    shields: 0,
    keywords: [],
    flavor: 'Half battery, half grudge.',
  },
  {
    type: 'order',
    defId: 'voss_arc_jolt',
    name: 'Arc Jolt',
    faction: 'voss',
    cost: 1,
    effects: [
      { kind: 'damage', amount: 2, target: 'enemyUnit' },
      { kind: 'damageOwnCaptain', amount: 1 },
    ],
    description: 'Overload: deal 2 damage to an enemy unit. Deal 1 damage to your own Captain.',
    flavor: 'It always costs something. That is the Voss way.',
  },
  {
    type: 'unit',
    defId: 'voss_interceptor',
    name: 'Voss Interceptor',
    faction: 'voss',
    unitKind: 'ship',
    cost: 2,
    attack: 3,
    hull: 2,
    shields: 0,
    keywords: ['rapidDeploy'],
    flavor: 'Faster than the sensors that are supposed to track it.',
  },
  {
    type: 'unit',
    defId: 'voss_reckless_drone',
    name: 'Reckless Drone',
    faction: 'voss',
    unitKind: 'creature',
    cost: 2,
    attack: 3,
    hull: 1,
    shields: 0,
    keywords: ['rapidDeploy'],
    flavor: 'It only has one setting: forward.',
  },
  {
    type: 'unit',
    defId: 'voss_current_cutter',
    name: 'Current Cutter',
    faction: 'voss',
    unitKind: 'ship',
    cost: 3,
    attack: 4,
    hull: 3,
    shields: 0,
    keywords: [],
    flavor: 'It cuts. That is the whole design brief.',
  },
  {
    type: 'order',
    defId: 'voss_overcharge_blast',
    name: 'Overcharge Blast',
    faction: 'voss',
    cost: 3,
    effects: [
      { kind: 'damage', amount: 4, target: 'enemyUnit' },
      { kind: 'damageOwnCaptain', amount: 1 },
    ],
    description: 'Overload: deal 4 damage to an enemy unit. Deal 1 damage to your own Captain.',
    flavor: 'Mira signs off on every reactor redline personally.',
  },
  {
    type: 'unit',
    defId: 'voss_reactor_adept',
    name: 'Reactor Adept',
    faction: 'voss',
    unitKind: 'creature',
    cost: 3,
    attack: 2,
    hull: 3,
    shields: 1,
    keywords: [],
    ability: { trigger: 'onPlay', effects: [{ kind: 'gainRP', amount: 1 }], description: 'When deployed, gain 1 Reactor Power this turn.' },
    flavor: 'She reads a dying reactor the way others read a room.',
  },
  {
    type: 'module',
    defId: 'voss_overcharged_capacitor',
    name: 'Overcharged Capacitor',
    faction: 'voss',
    cost: 2,
    attackBonus: 2,
    hullBonus: 0,
    shieldBonus: 0,
    keywordsGranted: [],
    ability: { trigger: 'onPlay', effects: [{ kind: 'damageOwnCaptain', amount: 1 }], description: 'When attached, deal 1 damage to your own Captain.' },
    flavor: 'More power than the hull was ever rated for.',
  },
  {
    type: 'unit',
    defId: 'voss_ionstorm_frigate',
    name: 'Ionstorm Frigate',
    faction: 'voss',
    unitKind: 'ship',
    cost: 4,
    attack: 5,
    hull: 3,
    shields: 0,
    keywords: ['cloak'],
    flavor: 'You do not see it until it has already fired.',
  },
  {
    type: 'module',
    defId: 'voss_feedback_loop',
    name: 'Feedback Loop',
    faction: 'voss',
    cost: 4,
    attackBonus: 0,
    hullBonus: 3,
    shieldBonus: 2,
    keywordsGranted: [],
    flavor: 'Some Voss tech is built to survive its own designers.',
  },
  {
    type: 'unit',
    defId: 'voss_static_dreadwing',
    name: 'Static Dreadwing',
    faction: 'voss',
    unitKind: 'ship',
    cost: 5,
    attack: 6,
    hull: 4,
    shields: 0,
    keywords: ['rapidDeploy'],
    flavor: 'It arrives already at full power. That is the problem.',
  },
  {
    type: 'order',
    defId: 'voss_blackout_surge',
    name: 'Blackout Surge',
    faction: 'voss',
    cost: 5,
    effects: [
      { kind: 'damage', amount: 6, target: 'enemyUnit' },
      { kind: 'damageOwnCaptain', amount: 2 },
    ],
    description: 'Overload: deal 6 damage to an enemy unit. Deal 2 damage to your own Captain.',
    flavor: 'Every ship in the Current dims for a second when this fires.',
  },
  {
    type: 'unit',
    defId: 'voss_vanguard_cadre',
    name: 'Voss Vanguard Cadre',
    faction: 'voss',
    unitKind: 'creature',
    cost: 6,
    attack: 5,
    hull: 5,
    shields: 2,
    keywords: ['boarding'],
    flavor: 'They board a wreck the way most people knock on a door.',
  },
  {
    type: 'module',
    defId: 'voss_singularity_coil',
    name: 'Singularity Coil',
    faction: 'voss',
    cost: 6,
    attackBonus: 4,
    hullBonus: 0,
    shieldBonus: 0,
    keywordsGranted: [],
    flavor: 'Banned in four systems. Standard issue in House Voss.',
  },
  {
    type: 'unit',
    defId: 'voss_unbroken_current_prime',
    name: 'Unbroken Current-Prime',
    faction: 'voss',
    unitKind: 'ship',
    cost: 7,
    attack: 8,
    hull: 6,
    shields: 1,
    keywords: ['rapidDeploy'],
    flavor: "Mira's flagship. Named for a promise she made at her mother's grave.",
  },
];
